/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Document } from "@contentful/rich-text-types";
export namespace Components {
    interface MediaBox {
        "imageAltText": string;
        "imageOrientation": string;
        "imageSource": string;
        "sectionDescription": string;
        "sectionTitle": Document;
    }
}
declare global {
    interface HTMLMediaBoxElement extends Components.MediaBox, HTMLStencilElement {
    }
    var HTMLMediaBoxElement: {
        prototype: HTMLMediaBoxElement;
        new (): HTMLMediaBoxElement;
    };
    interface HTMLElementTagNameMap {
        "media-box": HTMLMediaBoxElement;
    }
}
declare namespace LocalJSX {
    interface MediaBox {
        "imageAltText"?: string;
        "imageOrientation"?: string;
        "imageSource"?: string;
        "sectionDescription"?: string;
        "sectionTitle"?: Document;
    }
    interface IntrinsicElements {
        "media-box": MediaBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "media-box": LocalJSX.MediaBox & JSXBase.HTMLAttributes<HTMLMediaBoxElement>;
        }
    }
}
